apply plugin: "java"

sourceSets.main.java.srcDirs = ["src"]

repositories{
    mavenCentral()//总预备队不动

    //Downloads the dependencies JAR file from Mindustry releases; does not use any real repository. Surprisingly, this is the most reliable option.
    ivy{
        url = 'https://github.com/'
        patternLayout{artifact '/[organisation]/[module]/releases/download/[revision]/dependencies.jar'}
        metadataSources{ artifact() }
    }

    //If the version is set to 'latest', downloads the latest Mindustry *release* as a dependency
    ivy{
        url = 'https://github.com/'
        patternLayout{artifact '/[organisation]/[module]/releases/[revision]/download/dependencies.jar'}
        metadataSources{ artifact() }
    }

    //For depending on the absolute newest commit for Mindustry
    ivy{
        url = 'https://github.com/'
        patternLayout{artifact '/[organisation]/[module]/releases/download/master/[revision].jar'}
        metadataSources{ artifact() }
    }
}

ext{
    sdkRoot = System.getenv("ANDROID_HOME")
    mindustryVersion = "v160"
    isWindows = System.getProperty("os.name").toLowerCase().contains("windows")
}


tasks.withType(JavaCompile).configureEach {
    targetCompatibility = 17
    sourceCompatibility = JavaVersion.VERSION_17
    options.encoding = 'UTF-8'
}

dependencies{
    def localDesktop = isWindows ? file("D:/桌面/GAMES/MDT/jre/desktop.jar") : null//草不能直接?:会炸，得null一个
    if (localDesktop != null && localDesktop.exists()) {
        compileOnly files(localDesktop)
    } else {//走臭猫的库构建
        compileOnly mindustryVersion == "be" ? "Anuken:MindustryBuilds:latest" : "Anuken:Mindustry:$mindustryVersion"
    }
}

tasks.register('jarAndroid'){
    dependsOn jar
    def projectName = project.name

    doLast {
        if (!sdkRoot || !new File("$sdkRoot").exists())
            throw new GradleException("No valid Android SDK found. Ensure that ANDROID_HOME is set to your Android SDK directory.")

        def platformRoot = new File("$sdkRoot/platforms/").listFiles().sort().reverse().find { f -> new File(f, "android.jar").exists() }

        if (!platformRoot) throw new GradleException("No android.jar found. Ensure that you have an Android platform installed.")

        def buildToolsRoot = new File("$sdkRoot/build-tools/").listFiles().sort().reverse().find {
            f -> new File(f, isWindows ? "d8.bat" : "d8").exists()
        }

        if (!buildToolsRoot)
            throw new GradleException("No d8 found in build-tools. Ensure that a recent build-tools is installed.")

        def d8 = new File(buildToolsRoot, isWindows ? "d8.bat" : "d8").absolutePath

        def dependencies = (configurations.compileClasspath.asList() + configurations.runtimeClasspath.asList() + [new File(platformRoot, "android.jar")]).collect { "--classpath $it.path" }.join(" ")

        "$d8 $dependencies --min-api 14 --output ${projectName}Android.jar ${projectName}Desktop.jar"
                .execute(null, new File("build/libs")).waitForProcessOutput(System.out, System.err)
    }
}

jar{
    archiveFileName = "${project.name}Desktop.jar"

    duplicatesStrategy = DuplicatesStrategy.EXCLUDE

    from{
        configurations.runtimeClasspath.collect{ it.isDirectory() ? it : zipTree(it) }
    }

    from(projectDir){
        include "mod.hjson"
    }

    from("assets/"){
        include "**"
    }
}

tasks.register('deploy', Jar){
    dependsOn jarAndroid
    dependsOn jar
    archiveFileName = "${project.name}.jar"

    from{ [zipTree("build/libs/${project.name}Desktop.jar"), zipTree("build/libs/${project.name}Android.jar")] }

    doLast{
        delete{
            delete "build/libs/${project.name}Desktop.jar"
            delete "build/libs/${project.name}Android.jar"
        }
    }
}